name: build

on:
  push:
    branches: [ master ]
    paths:
      - 'src/Aiplugs.PoshApp.Deamon/**'
      - 'src/Aiplugs.PoshApp.Electron/**'
      - '.github/workflows/build.yml'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'src/Aiplugs.PoshApp.Deamon/**'
      - 'src/Aiplugs.PoshApp.Electron/**'
      - '.github/workflows/build.yml'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        node-version: 14.x
    - name: Build deamon
      working-directory: ./src/Aiplugs.PoshApp.Deamon/
      run: dotnet publish -c Release -r win10-x64 
    - name: Copy artifacts
      shell: bash
      working-directory: ./src
      run: |
        mkdir Aiplugs.PoshApp.Electron/bin/
        cp -r Aiplugs.PoshApp.Deamon/bin/Release/net5/win10-x64/publish/* Aiplugs.PoshApp.Electron/bin/
    - name: Install modules
      working-directory: ./src/Aiplugs.PoshApp.Electron/
      run: npm install
    - name: Build electron
      env:
        CSC_LINK: ${{ secrets.CSC_LINK_WIN }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD_WIN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./src/Aiplugs.PoshApp.Electron/
      run: npm run electron:build
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        node-version: 14.x
    - name: Build deamon
      working-directory: ./src/Aiplugs.PoshApp.Deamon/
      run: dotnet publish -c Release -r osx-x64
    - name: Copy artifacts
      shell: bash
      working-directory: ./src
      run: |
        mkdir Aiplugs.PoshApp.Electron/bin/
        cp -r Aiplugs.PoshApp.Deamon/bin/Release/net5/osx-x64/publish/* Aiplugs.PoshApp.Electron/bin/
    - name: Install modules
      working-directory: ./src/Aiplugs.PoshApp.Electron/
      run: npm install
    - name: Build electron
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        CSC_LINK: ${{ secrets.CSC_LINK_MAC }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD_MAC }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      working-directory: ./src/Aiplugs.PoshApp.Electron/
      run: npm run electron:build
