name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        node-version: 12.x
    - name: Install tool
      run: dotnet tool install--tool-path .tools ElectronNET.CLI
    - name: Move to project
      run: cd ./src/Aiplugs.PoshApp/
    - name: Build with dotnet
      run: ../../tools/electronize build /target win
