name: release

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Get plain tag name
      id: gettagname
      shell: pwsh
      run: echo "::set-output name=tag_name::$("${{ github.event.release.tag_name }}".Substring(1))"
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        node-version: 12.x
    - name: Install tool
      run: dotnet tool restore
    - name: Build with dotnet
      env:
        CSC_LINK: ${{ secrets.CSC_LINK_WIN }}
        CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD_WIN }}
      working-directory: ./src/Aiplugs.PoshApp/
      run: dotnet tool run electronize build /target custom "win10-x64;win"
    - name: Upload Release Asset1
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/Aiplugs.PoshApp/bin/Desktop/POSH App Setup ${{ steps.gettagname.outputs.tag_name }}.exe
        asset_name: POSH-App-Setup-${{ steps.gettagname.outputs.tag_name }}.exe
        asset_content_type: application/octet-stream
    - name: Upload Release Asset2
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/Aiplugs.PoshApp/bin/Desktop/POSH App Setup ${{ steps.gettagname.outputs.tag_name }}.exe.blockmap
        asset_name: POSH-App-Setup-${{ steps.gettagname.outputs.tag_name }}.exe.blockmap
        asset_content_type: application/octet-stream
    - name: Upload Release Asset3
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./src/Aiplugs.PoshApp/bin/Desktop/latest.yml
        asset_name: latest.yml
        asset_content_type: text/yaml
      
