name: release

on:
  release:
    types: [created]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Get plain tag name
        id: gettagname
        shell: pwsh
        run: echo "::set-output name=tag_name::$("${{ github.event.release.tag_name }}".Substring(1))"
      - name: test
        run: echo ${{ steps.gettagname.outputs.tag_name }}
      
