name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: iwate
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./src
          file: ./src/Aiplugs.PoshApp.Web/Dockerfile
          push: true
          tags: |
            ghcr.io/aiplugs/poshapp/web:latest
            ghcr.io/aiplugs/poshapp/web:${{ github.event.release.tag_name }}
