name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get plain tag name
        id: gettagname
        shell: pwsh
        run: |
          $tag = "${{ github.event.release.tag_name }}"
          $idx = $tag.IndexOf("-")
          if ($idx -ge 0) {
            $tag = $tag.Substring($idx+1)
            $idx = $tag.IndexOf(".")
            if ($idx -ge 0) {
              $tag = "ghcr.io/aiplugs/poshapp/web:$($tag.Substring(0, $idx)),ghcr.io/aiplugs/poshapp/web:${{ github.event.release.tag_name }}"
            }
          }
          else {
            $tag = "ghcr.io/aiplugs/poshapp/web:latest,ghcr.io/aiplugs/poshapp/web:beta,ghcr.io/aiplugs/poshapp/web:${{ github.event.release.tag_name }}"
          }
          echo "::set-output name=tag_name::$tag"
      
      - name: Prebuild
        shell: pwsh
        working-directory: ./src/Aiplugs.PoshApp.Electron/
        run: ./prebuild.ps1 linux-x64
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: iwate
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.gettagname.outputs.tag_name }}
