name: Publish Docker image
on:
  release:
    types: [prereleased]
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GHCR
        working-directory: ./src/
        run: |
          echo ${{ secrets.CR_PAT }} | docker login https://ghcr.io -u iwate --password-stdin
          docker build -f ./Aiplugs.PoshApp.Web/Dockerfile -t ghcr.io/aiplugs/poshapp/web:latest -t ghcr.io/aiplugs/poshapp/web:${{ github.event.release.tag_name }} ./
          docker push ghcr.io/aiplugs/poshapp/web:latest
          docker push ghcr.io/aiplugs/poshapp/web:${{ github.event.release.tag_name }}

    